# Generated by Django 5.1.6 on 2025-02-06 09:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SalaryComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("BASIC", "Basic Salary"),
                            ("HRA", "House Rent Allowance"),
                            ("DA", "Dearness Allowance"),
                            ("BONUS", "Performance Bonus"),
                            ("OTHER", "Other Allowance"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage of base salary",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_taxable", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("basic_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("hra", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "other_allowances",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "performance_bonus",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "pf_contribution",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("tax_deduction", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "leave_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "gross_earnings",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("net_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("BANK", "Bank Transfer"),
                            ("CASH", "Cash"),
                            ("CHEQUE", "Cheque"),
                        ],
                        default="BANK",
                        max_length=10,
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("remarks", models.TextField(blank=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="employees.employee",
                    ),
                ),
                (
                    "payroll_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payroll.payrollperiod",
                    ),
                ),
            ],
            options={
                "ordering": ["-payroll_period__start_date"],
                "unique_together": {("employee", "payroll_period")},
            },
        ),
    ]
